"""link league owner to user

Revision ID: 48e3728d8e45
Revises: e9c39dedd357
Create Date: 2026-03-08 15:46:23.504130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48e3728d8e45'
down_revision: Union[str, None] = 'e9c39dedd357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'league', 'user', ['owner_id'], ['id'])
    op.drop_column('league', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('owner', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'league', type_='foreignkey')
    op.drop_column('league', 'owner_id')
    # ### end Alembic commands ###
