"""decoupled_registration_from_roster

Revision ID: 4e7deaaff448
Revises: 
Create Date: 2026-03-13 17:28:26.287126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e7deaaff448'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id')
    )
    op.create_table('player',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('hltv_id', sa.Integer(), nullable=True),
    sa.Column('steam_id', sa.BigInteger(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('hltv_id'),
    sa.UniqueConstraint('steam_id')
    )
    op.create_table('team',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('hltv_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('hltv_id')
    )
    op.create_table('tournament',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('hltv_id', sa.Integer(), nullable=True),
    sa.Column('hltv_url', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('hltv_id')
    )
    op.create_table('league',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACTIVE', 'COMPLETED', name='leaguestatus'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('league_length', sa.Integer(), nullable=True),
    sa.Column('prize_description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('hltv_id', sa.Integer(), nullable=True),
    sa.Column('hltv_url', sa.Text(), nullable=True),
    sa.Column('demo_url', sa.Text(), nullable=True),
    sa.Column('demo_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='demo_download_status'), nullable=False),
    sa.Column('demo_retry_count', sa.Integer(), nullable=False),
    sa.Column('maximum_maps', sa.Integer(), nullable=False),
    sa.Column('tournament_uuid', sa.UUID(), nullable=True),
    sa.Column('team_a_uuid', sa.UUID(), nullable=True),
    sa.Column('team_b_uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['team_a_uuid'], ['team.uuid'], ),
    sa.ForeignKeyConstraint(['team_b_uuid'], ['team.uuid'], ),
    sa.ForeignKeyConstraint(['tournament_uuid'], ['tournament.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('hltv_id')
    )
    op.create_index('idx_match_demo_pending', 'match', ['demo_status'], unique=False, postgresql_where=sa.text("demo_status IN ('PENDING', 'FAILED')"))
    op.create_table('league_pool',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_teams', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('map',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('hltv_id', sa.Integer(), nullable=True),
    sa.Column('hltv_url', sa.Text(), nullable=True),
    sa.Column('match_uuid', sa.UUID(), nullable=True),
    sa.Column('map_name', sa.String(length=50), nullable=False),
    sa.Column('demo_parsed_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='demo_parsed_status'), nullable=False),
    sa.Column('demo_parse_retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_uuid'], ['match.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('hltv_id')
    )
    op.create_index('idx_map_demo_parse_pending', 'map', ['demo_parsed_status'], unique=False, postgresql_where=sa.text("demo_parsed_status IN ('PENDING', 'FAILED')"))
    op.create_table('game_stats',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('player_uuid', sa.UUID(), nullable=True),
    sa.Column('map_uuid', sa.UUID(), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['map_uuid'], ['map.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_uuid'], ['player.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('player_uuid', 'map_uuid', name='uq_game_stats_player_map')
    )
    op.create_table('league_registration',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('league_id', sa.UUID(), nullable=False),
    sa.Column('pool_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('REGISTERED', 'POOLED', 'DRAFTING', 'COMPLETED', name='registration_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['league_pool.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('account_id', 'league_id', name='uq_account_league_registration')
    )
    op.create_table('roster',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('pool_id', sa.Uuid(), nullable=False),
    sa.Column('registration_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['league_pool.uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['league_registration.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roster')
    op.drop_table('league_registration')
    op.drop_table('game_stats')
    op.drop_index('idx_map_demo_parse_pending', table_name='map', postgresql_where=sa.text("demo_parsed_status IN ('PENDING', 'FAILED')"))
    op.drop_table('map')
    op.drop_table('league_pool')
    op.drop_index('idx_match_demo_pending', table_name='match', postgresql_where=sa.text("demo_status IN ('PENDING', 'FAILED')"))
    op.drop_table('match')
    op.drop_table('league')
    op.drop_table('tournament')
    op.drop_table('team')
    op.drop_table('player')
    op.drop_table('account')
    # ### end Alembic commands ###
