"""create_roster_and_rename_user_to_account

Revision ID: 642a13b16b39
Revises: 48e3728d8e45
Create Date: 2026-03-13 16:07:14.789342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '642a13b16b39'
down_revision: Union[str, None] = '48e3728d8e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename user to account
    op.rename_table("user", "account")
    op.create_table('roster',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('league_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Removed drop table because we renamed it
    pass
    op.drop_constraint('league_owner_id_fkey', 'league', type_='foreignkey')
    op.create_foreign_key(None, 'league', 'account', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league', type_='foreignkey')
    op.create_foreign_key('league_owner_id_fkey', 'league', 'user', ['owner_id'], ['id'])
    op.rename_table('account', 'user')
    op.drop_table('roster')
    # Removed drop table because we renamed it
    pass
    # ### end Alembic commands ###
