"""add_league_lifecycle_timestamps

Revision ID: 6cc3731b76c7
Revises: 22ad575315d2
Create Date: 2026-03-16 20:37:28.438059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc3731b76c7'
down_revision: Union[str, None] = '22ad575315d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('pool_size', sa.Integer(), nullable=False))
    op.add_column('league', sa.Column('registration_deadline', sa.DateTime(), nullable=True))
    op.add_column('league', sa.Column('draft_start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league', 'draft_start_time')
    op.drop_column('league', 'registration_deadline')
    op.drop_column('league', 'pool_size')
    # ### end Alembic commands ###
